version: "3.9"

services:
  backend:
    build:
      context: ./services/backend
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  frontend:
    build:
      context: ./services/frontend
    command: npm run serve
    expose:
      - 9000
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
      - 1338:8080
    depends_on:
      - backend

volumes:
  postgres_data_prod:
